# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZJC
subtitle: Stay Hungry, Stay Foolish
description: "Zhangjicheng个人站，主要涉及前端知识共享、实践教程、前沿技术共同学习等方面"
keywords:
author: zhangjicheng
# next 主题语言
# language: zh-Hans
# icarus 主题语言
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://yoursite.com
url: https://zhangjichengcc.github.io/blog        # url地址
# url: https://zhangjichengcc.github.io             # url地址
root: /blog/                                      # 根目录          
# root: /                                           # 根目录          
permalink: :year/:month/:day/:title/              # 链接组合
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false # 是否显示草稿
post_asset_folder: true # 创建时生成静态资源文件夹
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: # 配置发布
  type: git
  # repository: https://github.com/zhangjichengcc/bolg.git
  repository: git@github:zhangjichengcc/zhangjichengcc.github.io.git
  branch: master
